# Generated by Django 6.0.1 on 2026-01-13 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0002_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher_assignments',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used as default password (DDMMYYYY format)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, help_text='Unique student identifier for login', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_stu_student_id'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.section'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core_services.teacher'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'session'], name='idx_ta_teacher_session'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['class_ref', 'section', 'session'], name='idx_ta_cls_sec_session'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_ref', 'section', 'subject', 'session')},
        ),
    ]
