# Generated by Django 6.0.1 on 2026-01-13 19:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0003_add_student_auth_and_teacher_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_teachers',
            },
        ),
        migrations.CreateModel(
            name='CocurricularTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cocurricular_teacher_assignments',
            },
        ),
        migrations.CreateModel(
            name='OptionalTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'optional_teacher_assignments',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred', 'Transferred Out'), ('graduated', 'Graduated'), ('dropped', 'Dropped Out')], default='active', max_length=20)),
                ('promotion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_enrollments',
                'ordering': ['-session__start_date', 'roll_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='session',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When locked, no academic/financial changes allowed'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_class',
            field=models.ForeignKey(blank=True, db_column='admission_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_session',
            field=models.ForeignKey(blank=True, db_column='admission_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_ref',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core_services.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core_services.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core_services.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Permanent unique student identifier', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_session'], name='idx_stu_admission_sess'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['class_ref', 'section', 'subject', 'session'], name='idx_ta_cls_sec_sub_sess'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='core_services.section'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='core_services.teacher'),
        ),
        migrations.AddField(
            model_name='cocurricularteacherassignment',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_teacher_assignments', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='cocurricularteacherassignment',
            name='cocurricular_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.cocurricularsubject'),
        ),
        migrations.AddField(
            model_name='cocurricularteacherassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_teacher_assignments', to='core_services.section'),
        ),
        migrations.AddField(
            model_name='cocurricularteacherassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_teacher_assignments', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='cocurricularteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_assignments', to='core_services.teacher'),
        ),
        migrations.AddField(
            model_name='optionalteacherassignment',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='optional_teacher_assignments', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='optionalteacherassignment',
            name='optional_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core_services.optionalsubject'),
        ),
        migrations.AddField(
            model_name='optionalteacherassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_teacher_assignments', to='core_services.section'),
        ),
        migrations.AddField(
            model_name='optionalteacherassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_teacher_assignments', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='optionalteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_assignments', to='core_services.teacher'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_services.class'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='promoted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_enrollment', to='core_services.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_services.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_services.session'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_services.student'),
        ),
        migrations.AddIndex(
            model_name='classteacher',
            index=models.Index(fields=['teacher', 'session'], name='idx_ct_teacher_session'),
        ),
        migrations.AddIndex(
            model_name='classteacher',
            index=models.Index(fields=['class_ref', 'section', 'session'], name='idx_ct_cls_sec_sess'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('class_ref', 'section', 'session')},
        ),
        migrations.AddIndex(
            model_name='cocurricularteacherassignment',
            index=models.Index(fields=['teacher', 'session'], name='idx_cta_teacher_session'),
        ),
        migrations.AlterUniqueTogether(
            name='cocurricularteacherassignment',
            unique_together={('class_ref', 'section', 'cocurricular_subject', 'session')},
        ),
        migrations.AddIndex(
            model_name='optionalteacherassignment',
            index=models.Index(fields=['teacher', 'session'], name='idx_ota_teacher_session'),
        ),
        migrations.AlterUniqueTogether(
            name='optionalteacherassignment',
            unique_together={('class_ref', 'section', 'optional_subject', 'session')},
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['session', 'class_ref', 'section'], name='idx_enroll_sess_cls_sec'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'session'], name='idx_enroll_stu_sess'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['status'], name='idx_enroll_status'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'session')},
        ),
    ]
